### ISSUE TITLE
Sort by prefix/bgpsec type is inverted

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#10]
If an user queries for prefix or bgpsec objects, sorting all the results by column "type", it is expected to display first all the prefixes or bgpsec registries that contains the "assertion" type followed by those with "filter" type. However, the sort brings first all the results with "filter" type instead of the "assertion" type.

It is necessary to fix the sort by type column for prefix and bgpsec queries.

**Comment by pcarana** [comment]
The issue was at DB level, since the type was stored as an Integer, the 'assertion' type had the ID 2 and the 'filter' type had the ID 1.

This has been changed and now the type is stored as a String.

**Comment by TheRedTrainer** [comment]
Verified. When a bgpsec or prefix query is sorted by type, the value is sorted as a String, not as a catalog id.
