### ISSUE TITLE
It is allowed to sort queries for duplicated parameters

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#11]
When an user queries for any object that could be sorted by "prefix", "prefixLength" and "prefixMaxLength" (such as roa, prefix assertion or prefix filter), it is possible to duplicate these sort parameters, beside the fact that it should be forbidden by the server. 

It is necessary to apply the restriction to avoid duplicated parameters for every parameter.

**Comment by pcarana** [comment]
The 'check for duplicates' validation at the sort parameter values wasn't correct, this has been fixed.

**Comment by TheRedTrainer** [comment]
Verified. If an user tries to sort any query by a duplicated parameter (including prefix, prefixLength and maxPrefixLength), the following message is displayed:

{
   code: 400 ,
   message: "The property 'prefix' is duplicated at the sort parameter"
}
