### ISSUE TITLE
Internal error when user add a bgpsec filter with an invalid SKI

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#2]
If an user tries to add a bgpsec filter for the slurm configuration with an invalid SKI, the server returns an internal error message.

The bgpsec filter is added using the following POST request 

**_localhost:8080/rpki-validator-api/slurm/bgpsec/filter_**

The json sent for the POST request contains the following data:

**_{
   "asn": 123,
   "SKI": "ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE1",
   "comment": "Esta es una prueba"
}_**

The server's response is the following json:

**_{
   "code":   500,
   "message":   "Internal Server Error, try again"
}_**

The server's log register the following stack trace 

> INFO: starting tree validation for ripe with id 5
> Oct 02, 2018 3:35:33 PM mx.nic.lab.rpki.api.result.error.ErrorResult <init>
> SEVERE: exception decoding Hex data: invalid characters encountered in Hex data
> org.bouncycastle.util.encoders.DecoderException: exception decoding Hex data: invalid characters encountered in Hex data
>         at org.bouncycastle.util.encoders.Hex.decode(Unknown Source)
>         at mx.nic.lab.rpki.api.servlet.slurm.SlurmBgpsecIdServlet.getSlurmBgpsecFromBody(SlurmBgpsecIdServlet.java:324)
>         at mx.nic.lab.rpki.api.servlet.slurm.SlurmBgpsecIdServlet.handlePost(SlurmBgpsecIdServlet.java:173)
>         at mx.nic.lab.rpki.api.servlet.slurm.SlurmBgpsecIdServlet.doApiDaRequest(SlurmBgpsecIdServlet.java:84)
>         at mx.nic.lab.rpki.api.servlet.slurm.SlurmBgpsecIdServlet.doApiDaRequest(SlurmBgpsecIdServlet.java:47)
>         at mx.nic.lab.rpki.api.servlet.DataAccessServlet.doApiRequest(DataAccessServlet.java:73)
>         at mx.nic.lab.rpki.api.servlet.ApiServlet.handleRequest(ApiServlet.java:121)
>         at mx.nic.lab.rpki.api.servlet.ApiServlet.doPost(ApiServlet.java:217)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)

**Comment by pcarana** [comment]
Now the exception is handled and a 400 error will be returned if the decoded SKI value isn't a valid HEX

**Comment by TheRedTrainer** [comment]
Verified. If the user tries to add a bgpsec filter that includes an invalid SKI, the following answer is provided by the server:

{
   "code": 400,
   "message": "The property SKI, once base64url decoded, isn't a valid HEX value"
}
