### ISSUE TITLE
INFO Level logging increases quickly the log file size

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#3]
If an admin configures the INFO level and the file handler in logging.properties for rpki-validator-api and the trust anchor validation daemon running every 10 min, the log file size increases quickly in a way that could affect the server's OS. Within 16 hours aprox, the log file increased its size to 26 GB, raising several alerts from the operating system (see image below).

![log rpki de 24 gb](https://user-images.githubusercontent.com/22969079/46441178-5b0e8700-c72b-11e8-942d-910cd94fd516.JPG)

It is necessary to warn the administrators and users about the risk of configuring the logging level as INFO. It is also necessary to check if all the current INFO logs are required for logging file.

**Comment by pcarana** [comment]
There was a pair of INFO logs that were written by each object at the repository, so that's too much information. Those logs were degraded to FINE level.

**Comment by TheRedTrainer** [comment]
Verified. Even if the logging properties is configured to register INFO logs and the server runs for several days, the size for the log file increases few megabytes, no gigabytes like it did it before. A lot of non critical INFO logs were removed from server logs.
