### ISSUE TITLE
"Prefix": "null/null" is displayed when the user queries for a prefix filter with an empty prefix

### ISSUE THREAD

**Issue by TheRedTrainer** [pcarana/rpki-validator-api#7]
If an user queries for a prefix filter that was created without a prefix (including only the asn and the comments), the following json is retrieved by the rpki-validator-api server:

{
    "id": 4001,
    "asn": 323256,
    "prefix": "null/null",
    "type": "filter",
    "comment": "Test"
}

The json should not display an invalid prefix value such as "null/null".

**Comment by pcarana** [comment]
If the prefix value, or the asn value is null, then the property isn't sent in the response.

Also, a similar update was made at the BGPsec response, but with the properties SKI and ASN.

**Comment by TheRedTrainer** [comment]
Verified. If there is any null value within any bgpsec/prefix object, the property that contains that null value is not included in json response.
